name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.5.0
  shared_preferences: ^2.2.3
  google_fonts: ^8.1.0
  flutter_svg: ^2.0.10
  pdf: ^3.11.1
  printing: ^5.13.3
  image_picker: ^1.1.2
  url_launcher: ^6.3.2

  # Biblioteca para fazer requisições HTTP para sua API



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.jpg
    - assets/images/arthur.jpg
    - assets/images/luan.png
    - assets/images/abner.jpg
    - assets/images/gabriel.jpg
    - assets/images/impacto_hero.svg
    - assets/images/dora_mascote.svg
    - assets/dados/municipios_por_uf.json